config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # root :to => 'products#index'

  resources :products
  resources :order_items

  resource :cart, only: [:show]
  resource :book, only: [:show]


end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # has_many :orders


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book

  def self.get_bestseller_list
    response = RestClient::Request.execute(method: :get, url: 'https://api.nytimes.com/svc/books/v3/lists/combined-print-and-e-book-fiction.json', headers: {api_key: ENV['NYT_API_KEY']})
  end

end

app/models/order.rb
class Order < ApplicationRecord
  # belongs_to :account
  has_many :order_items

  before_save :update_total
  before_create :update_status

  def calculate_total
    self.order_items.collect { |item| item.product.price * item.quantity }.sum
  end

  private

  def update_status
    if self.status == nil?
      self.status = "In progress"
    end
  end

  def update_total
    self.total_price = calculate_total
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  scope :total_quantity, -> { where("quantity >=?", OrderItem..order_id.last)}


end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order

  def current_order
    if session[:order_id]
      Order.find(session[:order_id])
    else
      Order.new
    end
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @response = Book.get_bestseller_list()
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @order_items = current_order.order_items
  end

end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  def create
      @order = current_order
      @item = @order.order_items.new(item_params)
      @order.save
      session[:order_id] = @order.id
      flash[:notice] = "Your order is added to the shopping cart"
      redirect_to products_path
    end

  def destroy
    @order = current_order
    @item = @order.order_items.find(params[:id])
    @item.destroy
    @order.save
    flash[:notice] = "Your order is removed from the shopping cart"
    redirect_to cart_path
  end


    private
    def item_params
      params.require(:order_item).permit(:quantity, :product_id)
    end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    sleep 1
    @products = Product.all
    @order_item = current_order.order_items.new
  end

  def show
    @product = Product.find(params[:id])
    render :display
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
      if @product.update(product_params)
        flash[:notice] = "Product is now updated"
        redirect_to products_path
      else
        render :edit
      end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    # binding.pry
    if @product.save
      flash[:notice] = "Product is now added to inventory"
      respond_to do |format|
        format.html { redirect_to products_url }
        format.js
      end
    else
      render :new
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "The product is removed from the inventory"
    redirect_to products_path
  end

private
  def product_params
    params.require(:product).permit(:name, :description, :price)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/show.html.erb
<div class="container">
  <h4><%= link_to "Return to Simpson's products", products_path %></h4>
</div>
<hr>

<h3 align="center">New York Times best selling books this week</h3>
<div class="container">
  <div class="thumbnail">
    <% data = JSON.parse(@response) %>
    <% data["results"]["books"].each do |book| %>
      <%= book["rank"] %>: <%= book["title"].titleize %>, by <%= book["author"] %> 
      <br>
    <% end %>
  </div>
</div>

<hr>
<div class="container">
  <%=  @response %>
</div>

app/views/carts/show.html.erb
<div class="container">
<% if @order_items.any? %>
  <% @order_items.each do |item| %>
    <p><%= item.product.name %> | <%= link_to "Delete", order_item_path(item), :data => {:confirm => "You sure?", :method => "delete"} %></p>
    <p> Unit Price: <%= number_to_currency item.product.price %> | Quantity: <%= item.quantity %> | Total Price: <%= number_to_currency (item.product.price * item.quantity) %></p>
  <% end %>
  <p>Your Total: <%= number_to_currency current_order.total_price %></p>
<% else %>
  <p>Your shopping cart is empty.</p>
<% end %>
</div>
<hr>

<div class="container">
  <h4><%= link_to "Back to Simpson's Action Figure Outlet", products_path %></h4>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>D'oh, there's an error!  Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class="navbar-brand"><%= link_to "Simpsons Action Figures Outlet", products_path %></div>
    </div>
      <ul class="nav navbar-nav">
        <% if @order_items %>
         <% else %>
          <li><%= link_to "Shopping cart", '/cart' %></li>
        <% end %>
      </ul>
    <ul class="nav navbar-brand navbar-right">
      <li>Test</li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECommerceSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <h4><%= flash[:alert] %></h4>
    <h4><%= flash[:notice] %></h4>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= render "layouts/errors", :object => @product %>

<div class="container">
<%= form_for @product, remote: true do |f| %>
  <div class="row">
    <div class="col-md-6">
      <%= f.label :name, "Name"%>
      <%= f.text_field :name, size: 30 %>
    </div>
    <div class="col-md-6">
    <%= f.label :description, "Description" %>
    <%= f.text_area :description, size: "40x10"%>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
    <%= f.label :price, "Price" %>
    <%= f.number_field :price %>
    </div>
    <div class="col-md-6">
      <%= f.submit "Update or Add Product" %>
    </div>
  </div>
<% end %>
</div>

<hr>
<div class="container">
  <h4><%= link_to "Go Home", products_path %></h4>
</div>

app/views/products/_product.html.erb
<div class="row">
  <div class="col-md-12" align="center">
    <div class="thumbnail">
    <p><%= link_to product.name, product_path(product) %> | <%= number_to_currency product.price %>
    <p><%= product.description %>
    </div>
  </div>
</div>

app/views/products/create.js.erb
$('#new_product_link').remove();
$('#all_products').show();
$('#all_products').append('<%= j render(@product) %>');

app/views/products/display.html.erb
<div class="container">
  <p>Admin: <%= link_to "Edit Product", edit_product_path(@product) %> | <%= link_to "Delete Product", product_path, :data => {
      :confirm => "You sure?", :method => "delete"
    } %></p>
</div>

<div class="container">
  <h3>Product Details</h3>
</div>

<div class="container">
  <h3><%= @product.name %></h3>
  <h4><%= @product.description %></h4>
  <h4><%= number_to_currency @product.price %></h4>
</div>

<div class="container">
  <h4><%= link_to "Go Home", products_path %></h4>
</div>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "form" %>

app/views/products/index.html.erb
<div class="container">
  <div class="jumbotron" align="center">
    <h2>Simpsons Action Figures Outlet</h2>
  </div>
</div>

<div class="container" id="all_products">
  <% @products.each do |product| %>
  <div class="row">
    <div class="col-md-12" align="center">
      <div class="thumbnail">
      <p><%= link_to product.name, product_path(product) %> | <%= number_to_currency product.price %>
      <p><%= product.description %>
      <%= form_for @order_item do |f| %>
        <%= f.hidden_field :product_id, value: product.id %>
        <%= f.number_field :quantity %>
        <%= f.submit "Add to cart" %></p>
      <% end %>
      </div>
    </div>
  </div>
  <% end %>
</div>
<hr>

<div class="container">
  <h4><%= link_to "Add a product", new_product_path, id: "new_product_link", remote: true %></h4>
</div>

<hr>
<div class="container">
  <h4><%= link_to "Check out your shopping cart", cart_path %></h4>
</div>

<div class="container">
  <h4><%= link_to "New York Times bestsellers this week (also a nasty NYT API call)", book_path %></h4>
</div>

app/views/products/new.html.erb
<h3>Add a New Product</h3>

<%= render "form" %>

app/views/products/new.js.erb
$('#new_product_link').hide().after('<%= j render("form") %>')